_target_: src.models.mnist_module.MNISTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.002
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 8600

net:
  _target_: src.models.components.cnn_mnist_deep.ConvNetDeep
  lin1_size: 256
  output_size: 10

# compile model for faster training with pytorch 2.0
compile: false
